
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="payment-block">
    <p>Formas de Pagamento</p>
    <div class="footer-icons">
        <img src=<?php echo $this->getViewFileUrl('images/pagamentos.png'); ?> alt="Formas de Pagamento">
    </div>
</div>
<div class="shipping-block">
    <p>Formas de Entrega</p>
    <div class="footer-icons">
        <img src=<?php echo $this->getViewFileUrl('images/entrega.png'); ?> alt="Formas de Entrega">
    </div>
</div>
<div class="certificate-block">
    <p>Segurança e Certificação</p>
    <div class="footer-icons">
        <img src=<?php echo $this->getViewFileUrl('images/cut-security.png'); ?> alt="Segurança e Certificação">
    </div>
</div>