<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-social">
  <div class="social-media">
    <img src=<?php echo $this->getViewFileUrl('images/facebook-like.png'); ?> alt="Curtir pagina">
    <div class="social">
      <img src=<?php echo $this->getViewFileUrl('images/instagram.svg'); ?> alt="Instagram">
      <img src=<?php echo $this->getViewFileUrl('images/fa-facebook-square.svg'); ?> alt="Facebook">
    </div>
  </div>
</div>