<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-links">
  <div class="block institutional">
    <h4><?= __('Institutional') ?></h4>
    <ul>
      <li><a href="#" title="Sobre a empresa">Sobre a empresa</a></li>
      <li><a href="#" title="Nossos produtos">Nossos produtos</a></li>
      <li><a href="#" title="Trabalhe conosco">Trabalhe conosco</a></li>
      <li><a href="#" title="Conheça nossa loja">Conheça nossa loja</a></li>
    </ul>
  </div>
  <div class="block my-account">
    <h4>Minha Conta</h4>
    <ul>
      <li><a href="#" title="Dados pessoais">Dados pessoais</a></li>
      <li><a href="#" title="Alterar senha">Alterar senha</a></li>
      <li><a href="#" title="Meus pedidos">Meus pedidos</a></li>
      <li><a href="#" title="Endereço de entrega">Endereço de entrega</a></li>
    </ul>
  </div>
  <div class="block doubts">
    <h4>Dúvidas</h4>
    <ul>
      <li><a href="#" title="Formas de envio">Formas de envio</a></li>
      <li><a href="#" title="Formas de pagamento">Formas de pagamento</a></li>
      <li><a href="#" title="Garantia e segurança">Garantia e segurança</a></li>
      <li><a href="#" title="Orçamentos">Orçamentos</a></li>
    </ul>
  </div>
  <div class="block contact">
    <h4><?= __('Contact') ?></h4>
    <div class="content">
      <div class="contact-us">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/fa-whatsapp.svg'))?>" alt="whatsapp">
        <span title="<?= __('Whatsapp') ?>">21 9 8096-9124</span>
      </div>
      <div class="contact-us">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/fa-map-marker.svg'))?>" alt="Localização">
        <span title="Localização">Eulina Ribeiro 100</span>
      </div>
      <div class="contact-us">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/fa-envelope.svg'))?>" alt="email">
        <span title="<?= __('Email') ?>">hypeconect@gmail.com</span>
      </div>
    </div>
  </div>
</div>