<div class="mais-inform">
  <div class="content-inform">
    <div class="freight block">
      <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/fa-truck.svg'))?>" alt="image">
      <div class="msg">
        <span class="green"><?= __('Free shipping')?></span>
        <span class="white"><?= __('on purchases over BRL 200.00')?></span>
      </div>
    </div>
    <div class="discount block">
      <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/fa-barcode.svg'))?>" alt="image">
      <div class="msg">
        <span class="green"><?= __('10% discount')?></span>
        <span class="white"><?= __('by bank slip or deposit')?></span>
      </div>
    </div>
    <div class="installment block">
      <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/fa-credit-card.svg'))?>" alt="image">
      <div class="msg">
        <span class="green"><?= __('Installment')?></span>
        <span class="white"><?= __('up to 12 installments without interest on the card')?></span>
      </div>
    </div>
    <div class="safe block">
      <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/fa-shield.svg'))?>" alt="image">
      <div class="msg">
        <span class="green"><?= __('100% safe')?></span>
        <span class="white"><?= __('here you can trust')?></span>
      </div>
    </div>
  </div>
</div>