<div class="first-banner">
  <div class="slider-content">
    <div class="img-banner first">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/hypeconect-inicial.jpg'))?>" alt="image">
    </div>
    <div class="img-banner second">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/hypeconect-inicial.jpg'))?>" alt="image">
    </div>
    <div class="img-banner third">
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/hypeconect-inicial.jpg'))?>" alt="image">
    </div>
  </div>
</div>

<script type="text/x-magento-init">
  {
    ".slider-content": {
      "Magento_Theme/js/slick-slider": {}
    }
  }
</script>